{% set version = "4.25.0" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  sha256: e63acf5c11762c0e6672ffb61482bdf57f0876684d8d249c0fe2d730d48bc55f

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v
  entry_points:
    - jsonschema = jsonschema.cli:main

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python
    - attrs >=22.2.0
    - jsonschema-specifications >=2023.03.6
    - referencing >=0.28.4
    - rpds-py >=0.7.1

test:
  imports:
    - jsonschema
  requires:
    - pip
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help


about:
  home:  https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
  doc_url: https://python-jsonschema.readthedocs.io
  dev_url: https://github.com/python-jsonschema/jsonschema

extra:
  feedstock-name: jsonschema
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl
