{% set version = "4.26.0" %}
{% set name = "jsonschema" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c26707e2efad8aa1bfc5b7ce170f3fccc2e4918ff85989ba9ffa9facb2be326

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v
  entry_points:
    - jsonschema = jsonschema.cli:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python
    - attrs >=22.2.0
    - jsonschema-specifications >=2023.03.6
    - referencing >=0.28.4
    - rpds-py >=0.25.0

test:
  imports:
    - jsonschema
  requires:
    - pip
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help


about:
  home:  https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
  doc_url: https://python-jsonschema.readthedocs.io
  dev_url: https://github.com/python-jsonschema/jsonschema

extra:
  feedstock-name: jsonschema
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl
