{% set version = "4.17.3" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  sha256: 0f864437ab8b6076ba6707453ef8f98a6a0d512a80e93f8abdb676f737ecb60d
  patches:
    - patches/001-remove-fancy-pypi-readme.patch
build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps
  entry_points:
    - jsonschema = jsonschema.cli:main

requirements:
  build:
    - patch                # [unix]
    - m2-patch             # [win]

  host:
    - python
    - pip
    - wheel
    - hatchling
    - hatch-vcs
  run:
    - python
    - attrs >=17.4.0
    - pyrsistent !=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
    - importlib_metadata  # [py<38]
    - typing_extensions  # [py<38]
    - importlib_resources >=1.4.0  # [py<39]
    - pkgutil-resolve-name >=1.3.10  # [py<39]

test:
  imports:
    - jsonschema
  requires:
    - pip
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help


about:
  home:  https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
  doc_url: https://python-jsonschema.readthedocs.org
  doc_source_url: https://github.com/python-jsonschema/jsonschema/tree/main/docs
  dev_url: https://github.com/python-jsonschema/jsonschema

extra:
  feedstock-name: jsonschema
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl
