{% set version = "4.9.1" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  sha256: 408c4c8ed0dede3b268f7a441784f74206380b04f93eb2d537c7befb3df3099f

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jsonschema = jsonschema.cli:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm >=3.4
    - toml
    - wheel
  run:
    - python >=3.7
    - attrs >=17.4.0
    - importlib_metadata  # [py<38]
    - importlib_resources>=1.4.0  # [py<39]
    - pyrsistent !=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
    - typing_extensions  # [py<38]

test:
  imports:
    - jsonschema
  requires:
    - pip
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help 


about:
  home: https://github.com/Julian/jsonschema
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
  doc_url: https://python-jsonschema.readthedocs.org
  doc_source_url: https://github.com/python-jsonschema/jsonschema/blob/v4.9.1/docs/index.rst
  dev_url: https://github.com/python-jsonschema/jsonschema

extra:
  feedstock-name: jsonschema
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl