travis:
  secure:
    BINSTAR_TOKEN: mGkI8189qcqbvtxZFh7khCQFSfAPE/BwIPfFZUUdH+tGHzRdLLB/fu1EnVSpC/DoQqlamVC8UL+hULjMsuWZXbEi+ig45tLtyRX6i4jjsGfMOEtlnrwY2f4kmBeBNw7ZlIFUV4dVaXlrgNwlDOsUpUsdeR7MckXT/mJy6AOQBuV4qHpoUG3OMCzz+q5gwp+OJ77/LAB1nPUL7YsiYLOShIm5lbYDbZ7B4aqpwG/qyhOKE3td/FOuIDYz/xMR1FcFJE9dBPg9aIEOoExBM4oHiqJdncz+SwnUICQx9vG92pQaOGVW4NMhgyKS58ew98HVoK3ZEjKZ8/v05XefBpGlHTdZGg62F5PSIP8ViOiPJIxkQzeYZen8y2dW9AYZdxXasvlgk9mXqZSYCyv+Yf9+S38M25jwAtyXEiSAh4D/u8okRwBz13ByWJUI4kEFvWuaFftSeFKkI1fSrlW5TW4GNVDPhIB7IfcWd6VsKLvLr2QyiF7Aw1XAwnRC6+8l9VZEz/HOfYSpJh2LVsGwyHgP3zU4ot+QCtmxn8Uyty1yFpvv4BnN/sTuJ7dqaZ1XkGUCfWCs60UZbcFc3RNzUePeV5RelMUrXL7yuUOm8rvYC/SW5r3oOZB0rRRvYlNQHhlaTDLdN0bT21TXmPAYCJvIBCJy84iOxMCLtAPSE7LSPm0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
