travis:
  secure:
    BINSTAR_TOKEN: JfOJSQVE0kd1GWk9zBx5lyqkBHMEFjX6OjzFV1azDP4MY8apTsYzMZjr5M3pQLJMRiVXiKYpTL+lHST0r2BPO84bgispXGqxjcNxIXs9KUSzsEe/18iA+46q/ef6JoB/xrFv571EcAwd/g5C2onZGZmpWpBjsaTzHKzcy3iDMDtr5NOUf4d1JDBTPdlNLm0Axmm5zLd+X42nNgJfCcTUQ7DWtdZEV091r8rb3aYEEJovwQx2TNqik55/POtIB/5+MORts/Q8zQRM6ZzfPkxlTMSgGCOQJaXevSWN58jYmKwcxbLusZd48wlPVe+M4bfh24tIAESifOwLEuJfMtMX0SU3m7dxw9J4Rs5fTDDXoqA5lx3z82GzVN6BZKbpLODhI2mPrLx+4DxPKKX2AB/CyJkSZ9OdW9ePg1650Rstf19TjAXiSb83dXz8jQZVmUQc72gAeKQ33uI43j/xUMXKFxc8xdwPTcKJ/52doeN7PvLK6SNNgCVF7jBl81Kf3zJjrR9tZ/U5K8+laO8yaFP/qpgUCI36B7TRF3OZ70A2f9YEYKhY5XzLdjbYfiBYSTvpcXCr8I80mn3nhgCfDxbyL+pnBtKaP9E4OLoZp+gNLZxGRFAOaqBBUW89ceinO8DqwddmXAzRzvJeCLtATSziLGRr/l0/6jnYIK2opQL5vXk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
